### ISSUE TITLE
s390x CI failure: BoltSamplerSpec > should display results if asked fails at response.getTime()

### ISSUE THREAD

**Issue by AlocJose** [apache/jmeter#5919]
### Expected behavior

CI should pass

### Actual behavior

CI job failure observed on below task
https://builds.apache.org/job/JMeter/job/JMeter%20s390x/56/

Task :src:protocol:bolt:test FAILED

Details:
```
FAILURE   0.4sec, org.apache.jmeter.protocol.bolt.sampler.BoltSamplerSpec > should display results if asked
    Condition not satisfied:
    
    response.getTime() > 0
    |        |         |
    |        0         false
    org.apache.jmeter.samplers.SampleResult@485caa8f
    
        at org.apache.jmeter.protocol.bolt.sampler.BoltSamplerSpec.should display results if asked(BoltSamplerSpec.groovy:102)

FAILURE   2.9sec,    7 completed,   1 failed,   0 skipped, org.apache.jmeter.protocol.bolt.sampler.BoltSamplerSpec
          0.3sec,    1 completed,   0 failed,   0 skipped, org.apache.jmeter.resources.ResourceKeyUsageTestBolt
FAILURE   6.5sec,    8 completed,   1 failed,   0 skipped, Gradle Test Run :src:protocol:bolt:test

8 tests completed, 1 failed
```

This failure is observed intermittently.

### Steps to reproduce the problem

Execute CI job.

### JMeter Version

master

**Comment by AlocJose** [comment]
We tried the CI steps locally but couldn't observe any failure. Could you please share the node configurations which are used for the CI job?

**Comment by vlsi** [comment]
Thanks for the analysis.

Frankly speaking, I do not think the failure is specific to s390x.
The test expects "sampler duration" to exceed 0ms.
I think it is a wrong assumption and adds no value.

I think the response was blazing fast (which might be caused by s390x being too fast), so `response.getTime()` turned out to be `0`.

We probably need to remove that check or rework it somehow to ensure it returns non-negative results.

Do you think you could create such a PR?
